export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    me: '/auth/me',
    sendOtp: '/auth/send-otp',
    verifyOtp: '/auth/verify-otp',
    resendOtp: '/auth/resend-otp',
    forgotPasswordSendOtp: '/auth/forgot-password/send-otp',
    forgotPasswordVerifyOtp: '/auth/forgot-password/verify-otp',
    forgotPasswordReset: '/auth/forgot-password/reset',
    logout: '/auth/logout',
  },
  admin: {
    users: '/admin/users',
    blockUser: (id: string) => `/admin/users/${id}/block`,
    unblockUser: (id: string) => `/admin/users/${id}/unblock`,
    createAdmin: '/admin/create-admin',
    makeAdmin: (id: string) => `/admin/users/${id}/make-admin`,
    removeAdmin: (id: string) => `/admin/users/${id}/remove-admin`,
    grids: '/admin/grids',
    grid: (id: string) => `/admin/grids/${id}`,
    updateGrid: (id: string) => `/admin/grids/${id}`,
    openGrid: (id: string) => `/admin/grids/${id}/open`,
    closeGrid: (id: string) => `/admin/grids/${id}/close`,
    setWinningNumber: (id: string) => `/admin/grids/${id}/winning-number`,
    userHistory: (id: number | string) => `/admin/users/${id}/history`,
  },
  grid: {
    active: '/grid/active',
    numbers: (gridId: string) => `/grid/${gridId}/numbers`,
    subTickets: (gridId: string, number: number) => `/grid/${gridId}/numbers/${number}/subtickets`,
    buy: (gridId: string) => `/grid/${gridId}/buy`,
  },
  raffles: {
    open: '/raffles/open',
    one: (id: string) => `/raffles/${id}`,
    buy: (id: string) => `/raffles/${id}/buy`,
    myTickets: '/raffles/my-tickets',
    adminList: '/raffles/admin/list/all',
    adminCreate: '/raffles/admin/create',
    adminOpen: (id: string) => `/raffles/admin/${id}/open`,
    adminClose: (id: string) => `/raffles/admin/${id}/close`,
  },

  wallet: {
    mine: '/wallet',
    topUp: '/wallet/topups',
    withdraw: '/wallet/withdrawals',
    adminOverview: '/wallet/admin/overview',
    adminApproveTopUp: (id: string | number) => `/wallet/admin/topups/${id}/approve`,
    adminRejectTopUp: (id: string | number) => `/wallet/admin/topups/${id}/reject`,
    adminCompleteWithdrawal: (id: string | number) => `/wallet/admin/withdrawals/${id}/complete`,
    adminRejectWithdrawal: (id: string | number) => `/wallet/admin/withdrawals/${id}/reject`,
    adminAdjustUser: (id: string | number) => `/wallet/admin/users/${id}/adjust`,
  },
  payments: {
    list: '/payments',
    create: '/payments',
    one: (id: string | number) => `/payments/${id}`,
    slip: (id: string | number) => `/payments/${id}/slip`,
    adminList: '/payments/admin/list',
    adminApprove: (id: string | number) => `/payments/admin/${id}/approve`,
    adminReject: (id: string | number) => `/payments/admin/${id}/reject`,
  },
   draws: {
    active: '/draws/active',
    list: '/draws',
close: (id: string | number) => `/draws/${id}/close`  },

  tickets: {
    mine: '/tickets/mine',
    create: '/tickets',
    update: (id: string | number) => `/tickets/${id}`,
  },
}
